### ISSUE TITLE
Minecraft failed to start- Stoneblock 2

### ISSUE THREAD

**Issue by timmydrakewings** [p455w0rd/p455w0rds-Library#35] opened 2019-06-30 19:43 UTC
Every time I try to load Stoneblock 2 I get an error message that Minecraft failed to start, and it only lists this mod as a potential problem.
Here is the link to the error
https://paste.dimdev.org/woqofofaxu.mccrash

**Comment by p455w0rd** [comment] 2019-07-20 19:12
dupe of #31

**Closed as completed by p455w0rd** 2019-07-20 19:12 UTC
Labels: duplicate
