### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by runescapejon** [p455w0rd/p455w0rds-Library#39] opened 2019-07-03 01:53 UTC
Here are my versions
-AE2WTLib-1.12.2-1.0.30 
- appliedenergistics2-rv6-stable-6
- WirelessCraftingTerminal-1.12.2-3.12.93
- p455w0rdslib-1.12.2-2.2.151

https://gyazo.com/745669c8c49e6745f085c611cb2dec70
It seem whenever https://github.com/p455w0rd/p455w0rds-Library/blob/1.12/src/main/java/p455w0rdslib/LibEvents.java#L250-L287 these are called it start to lag really bad any idea how to improve it ? thank you

**Comment by p455w0rd** [comment] 2019-07-03 02:45
dupe of #33

**Closed as completed by p455w0rd** 2019-07-03 02:45 UTC
Labels: duplicate
