### ISSUE TITLE
Player crash when loading new chunks or entering already made chucks.

### ISSUE THREAD

**Issue by CapturedCherry-zz** [p455w0rd/p455w0rds-Library#40] opened 2019-07-06 16:10 UTC
When loading a chuck some times the game will crash with the following crash log. I'm not 100% sure if it is a p455w0rdslib issues or if its a forestry mod. https://gist.github.com/RiptideC27/fa5f509b5b6838352eaae5715594f480
I'm using the latest version of p455w0rdslib and forge.
If you can confirm that is isn't causing p455w0rdslib the issues then that would be great thank you.

**Comment by DrWhovahkiin** [comment] 2019-07-07 19:58
same as other issues posted. He's marking them as closed and fixed in dev, but I haven't seen any commits in like almost a month soo.. when can we actually get this new release that fixes these issues?

**Comment by p455w0rd** [comment] 2019-07-20 19:12
dupe of #30

**Closed as completed by p455w0rd** 2019-07-20 19:12 UTC
Labels: duplicate
