### ISSUE TITLE
Im in a server, crashes my whole game when in nether. closes my minecraft

### ISSUE THREAD

**Issue by ghost** [p455w0rd/p455w0rds-Library#42] opened 2019-07-12 17:00 UTC
https://pastebin.com/gXC2bZbU
crash report above.
thanks

**Comment by runescapejon** [comment] 2019-07-12 20:27
Duplicate of https://github.com/p455w0rd/p455w0rds-Library/issues/32

**Closed as completed** 2019-07-20 16:04 UTC
Labels: duplicate
