### ISSUE TITLE
Crash with randomthings coils and others

### ISSUE THREAD

**Issue by SirAron111** [p455w0rd/p455w0rds-Library#32] opened 2019-06-23 17:24 UTC
https://pastebin.com/6yT91NZ3 found a crash that happens on certain light blocks or blocks that do some light effects

**Comment by the-vindex** [comment] 2019-06-30 00:42
I get similar crash, just with different mod on top of stack trace https://pastebin.com/LAtYDiSr

**Comment by krisjenner** [comment] 2019-07-18 14:04
Players on my server experiencing the same V2.2.151 
[Crash](https://gist.github.com/krisjenner/bcd010988a2eed854ca72871c6cdb538)

**Comment by p455w0rd** [comment] 2019-07-20 19:08
dupe of #30

**Closed as completed by p455w0rd** 2019-07-20 19:08 UTC
Labels: duplicate
